language: go

go:
  - 1.2

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov

after_success:
  - $(echo $GOPATH | cut -d ':' -f 2)/bin/goveralls -v -coverprofile=profile.cov -service=travis-ci
