language: go

go:
  - 1.2

env:
  global:
    - COVERALLS_TOKEN=RvJ8hng3HdBB9IFfvoREmFKHezP8H09LS

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov

after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN
