language: go

go:
  - 1.2

install:
  # for go test -covermode=count
  - go get code.google.com/p/go.tools/cmd/cover
  # for goveralls using gocov
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go test -covermode=count -coverprofile=profile.cov

after_success:
  - goveralls -v -service=travis-ci
