language: go

go:
  - 1.2

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov

after_success:
  - sed -e "s|^github.com/ksoichiro/fint||" profile.cov > coveralls.cov
  - $HOME/gopath/bin/goveralls -v -coverprofile=coveralls.cov -service=travis-ci
